### ISSUE TITLE
Extend CI workflow

### ISSUE THREAD

**Issue by friendlyanon** [MarcDirven/cpp-lazy#13]
Right now the CI workflow only runs on Ubuntu and whatever [default compiler](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md) it comes set up with.

I'd like to get some feedback on what are desirable compilers and what version(s) of them would you like to have running in CI?

Also, if the CI workflow will be extended to many OSs and compiler versions, I believe that only a single job should be dedicated to running tests with the default compiler, where the library is installed and imported using `find_package`.

**Comment by MarcDirven** [comment]
As for the desirable compilers, I'd like to see at least Clang, GCC and the MSVC compiler as well. As for its corresponding versions, I'd like to see an older one and a newer one. The old travis configuration compiled the tests with `clang version 7.0.0 (tags/RELEASE_700/final)` and `gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609`. I think it would be nice to compile the tests with even older compilers; one that at least supports C++11 and a configuration where the tests gets compiled with the most recent compilers, so we have some sort of "best of both worlds" situation.

As for the single job part & running tests with the default compiler, I give you complete freedom in that, CMake and CI are not my strongest skills. I think you know better than me what's best practice for CMake and CI terrain.

**Comment by MarcDirven** [comment]
> 
> 
> Right now the CI workflow only runs on Ubuntu and whatever [default compiler](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md) it comes set up with.
> 
> I'd like to get some feedback on what are desirable compilers and what version(s) of them would you like to have running in CI?
> 
> Also, if the CI workflow will be extended to many OSs and compiler versions, I believe that only a single job should be dedicated to running tests with the default compiler, where the library is installed and imported using `find_package`.

As for the desirable compilers, I'd like to see at least Clang, GCC and the MSVC compiler as well. As for its corresponding versions, I'd like to see an older one and a newer one. The old travis configuration compiled the tests with clang version 7.0.0 (tags/RELEASE_700/final) and gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609. I think it would be nice to compile the tests with even older compilers; one that at least supports C++11 and a configuration where the tests gets compiled with the most recent compilers, so we have some sort of "best of both worlds" situation.

As for the single job part & running tests with the default compiler, I give you complete freedom in that, CMake and CI are not my strongest skills. I think you know better than me what's best practice for CMake and CI terrain.

**Comment by friendlyanon** [comment]
Hmm, so the library itself has to be built with specific versions of compilers, but the tests aren't.  
That means that in the regular cases the target compiler is used to build and install, and for the tests whatever else can used. Something like so:
```bash
CXX=clang++-7 cmake -S . -B build/lib
cmake --build build/lib
cmake --install build/lib
cmake -S tests -B build/tests -D TEST_INSTALLED_VERSION:BOOL=YES # no CXX passed
cmake --build build/tests
cd build/tests && ctest
```
Since 2 compilers in one CMake run can't be used, the library must be installed.

**Comment by MarcDirven** [comment]
> Hmm, so the library itself has to be built with specific versions of compilers, but the tests aren't.

Sorry, I meant the build _and_ the tests must be made with GCC, Clang and MSVC. These three compilers must contain an old and a new(er) version.

The reason for that, by the way, is because in the past, I have had no problems building with the latest compiler version locally, but the older compiler versions sometimes suddenly gave a build error (in the former CI, that used Travis).

**Comment by friendlyanon** [comment]
Well then, I have [this run](https://github.com/friendlyanon/cpp-lazy/actions/runs/298453789) where GCC 4.8 seems to not be able to link and VS2017 is complaining about missing headers.

Furthermore, I have to inject the PIC flag into the {fmt} directory scope to get things to link properly. See [this log](https://github.com/friendlyanon/cpp-lazy/runs/1233691103?check_suite_focus=true).

**Comment by MarcDirven** [comment]
Alright, could you make a PR for the CI tweaks you made so far? Then I can try to fix these issues.

**Comment by friendlyanon** [comment]
Any idea what the Position Independent Code requirement could be about?  
It seems weird that the `-fPIC` flag has to be injected to link against fmt.a

**Comment by MarcDirven** [comment]
Whoops, closed PR per accident. I've read that this `-fPIC` flag is for CPU's without MMU, which doesn't make sense, or for making shared libraries but that also doesn't make sense. I've seen [this](https://github.com/fmtlib/fmt/pull/446) issue and [this](https://github.com/fmtlib/fmt/issues/548) issue that may help. I'll try and do some more research on this, otherwise I'll just ask the guys of fmt on the same issue I've already created regarding the `mbig-obj` flag.

I'll create a development branch, good point.

**Comment by friendlyanon** [comment]
The issue closing was intentional with the inclusion of specific terms in the PR description, eg `fixes#nn`. This issue was opened for feedback about the extensions of the CI workflow, which I think we seccessfully discussed.  
There is no problem with keeping it closed but continuing related discussion.

Regarding `-fPIC`, since {fmt} [does not define library type](https://github.com/fmtlib/fmt/blob/master/CMakeLists.txt#L194), that `add_library` call is affected by [`BUILD_SHARED_LIBS`](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html)'s value, which by default is not defined, hence false, ie {fmt} is built as a static library as evident by the `fmt.a` artifact name.  
Your library is explicitly defined as `INTERFACE` (usage requirements only) and for the tests it's consumed directly using an executable target.  
Indeed, this doesn't make much sense.

**Comment by MarcDirven** [comment]
> The issue closing was intentional with the inclusion of specific terms in the PR description, eg fixes#nn. This issue was opened for feedback about the extensions of the CI workflow, which I think we seccessfully discussed.
There is no problem with keeping it closed but continuing related discussion.

Right, I'll close this for now. I've also asked {fmt} what's up with the `-fPIC` flag.
