### ISSUE TITLE
still support gcc5?

### ISSUE THREAD

**Issue by toge** [MarcDirven/cpp-lazy#133]
Does cpp-lazy support gcc5?
I met compilation error in gcc 5.4.0:
```
In file included from xxx/include/Lz/Map.hpp:6:0,
xxx/include/Lz/detail/BasicIteratorView.hpp:642:34: error: expected type-specifier before ‘MAKE_BIN_OP’
          class BinaryPredicate = MAKE_BIN_OP(std::equal_to, internal::ValueTypeIterable<IterableA>)>
                                  ^
xxx/include/Lz/detail/BasicIteratorView.hpp:642:34: error: expected ‘>’ before ‘MAKE_BIN_OP’
```

I already confirmed cpp-lazy works fine gcc 6.4.0 or later.

**Comment by MarcDirven** [comment]
This is surprising. It should though, will take a look at it when I have the time.

**Comment by MarcDirven** [comment]
Should be fixed in https://github.com/MarcDirven/cpp-lazy/commit/a511a620ac22582380bc6aa492d0ff649798e374

**Comment by toge** [comment]
@MarcDirven 
Thanks a lot!
I am going to try.

**Comment by MarcDirven** [comment]
Let me know if it works so we can close the issue

**Comment by toge** [comment]
@MarcDirven 
I confirmed it works fine.
I close this issue.
Thanks.
